version: "3.8"
services:
  db:
    image: postgres
    container_name: miraq_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miraq
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
